/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.loqoo.streets;

public final class R {
    public static final class anim {
        public static final int flipin=0x7f040000;
        public static final int flipout=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int and=0x7f020000;
        public static final int border=0x7f020001;
        public static final int borderl=0x7f020002;
        public static final int boys=0x7f020003;
        public static final int circle=0x7f020004;
        public static final int dope=0x7f020005;
        public static final int fivefiftyfive=0x7f020006;
        public static final int fiveforty=0x7f020007;
        public static final int girls=0x7f020008;
        public static final int ic_launcher=0x7f020009;
        public static final int kt_logo=0x7f02000a;
        public static final int splashlogo=0x7f02000b;
        public static final int washav540back=0x7f02000c;
        public static final int washav540front=0x7f02000d;
        public static final int washav555back=0x7f02000e;
        public static final int washav555front=0x7f02000f;
    }
    public static final class id {
        public static final int custom=0x7f070013;
        public static final int find_coordinates_button=0x7f070008;
        public static final int fivefiftyfive=0x7f070018;
        public static final int fivefiftyfive1=0x7f070019;
        public static final int fiveforty=0x7f070015;
        public static final int fstwash=0x7f070014;
        public static final int point_latitude=0x7f070006;
        public static final int point_longitude=0x7f070007;
        public static final int prox=0x7f070005;
        public static final int save_point_button=0x7f070009;
        public static final int splash_and=0x7f07000e;
        public static final int splash_boys=0x7f07000d;
        public static final int splash_dope=0x7f07000c;
        public static final int splash_flipper=0x7f07000b;
        public static final int splash_girls=0x7f07000f;
        public static final int splash_kt=0x7f070010;
        public static final int splashlogo=0x7f070003;
        public static final int standard=0x7f070012;
        public static final int test=0x7f07000a;
        public static final int towashave_ew_miafl_usa=0x7f070004;
        public static final int txtLat=0x7f070000;
        public static final int txtLong=0x7f070001;
        public static final int txtPostalCode=0x7f070002;
        public static final int washav_east_biz=0x7f070017;
        public static final int washav_east_sidewalk=0x7f07001a;
        public static final int washav_west_biz=0x7f070011;
        public static final int washav_west_sidewalk=0x7f070016;
        public static final int webview=0x7f07001b;
    }
    public static final class layout {
        public static final int connect=0x7f030000;
        public static final int fadein=0x7f030001;
        public static final int fadeout=0x7f030002;
        public static final int main=0x7f030003;
        public static final int prox=0x7f030004;
        public static final int splash1=0x7f030005;
        public static final int washave_ew_miafl_usa=0x7f030006;
        public static final int webview=0x7f030007;
    }
    public static final class raw {
        public static final int power=0x7f050000;
    }
    public static final class string {
        public static final int c=0x7f060002;
        public static final int custom=0x7f060000;
        public static final int standard=0x7f060001;
    }
}
